---

 - name: Install CartoDB apt dependencies
   apt: name={{ item }} state=present
   with_items:
     - python-all-dev
     - imagemagick
     - unp
     - zip

 - name: Install ruby gem dependencies
   apt: name={{ item }} state=present
   with_items:
     - libreadline6-dev
     - openssl

 - name: Install ruby gems
   gem: name={{ item }} state=present user_install=no
   with_items:
     - bundler
     - compass

 - name: Add RAILS_ENV variable to global environment
   lineinfile: dest=/etc/environment line="RAILS_ENV={{ cartodb_environment }}"

 - name: Install ruby bundle
   bundler: state=present chdir="{{ cartodb_dir }}"
   become_user: "{{ ansible_ssh_user }}"

 - name: Install global node packages
   npm: name={{ item }} state=present global=yes
   with_items:
     - grunt-cli

 - name: Install node packages
   npm: path={{ cartodb_dir }}
   become_user: "{{ ansible_ssh_user }}"

 - name: Upgrade pip to latest version
   pip: name=pip state=latest

 - name: Install python packages
   pip: requirements=python_requirements.txt chdir={{ cartodb_dir }} extra_args='--no-use-wheel'
   environment:
     CPLUS_INCLUDE_PATH: /usr/include/gdal
     C_INCLUDE_PATH: /usr/include/gdal
     PATH: "{{ ansible_env.PATH }}:/usr/include/gdal"
