---

 - name: Precompile static assets
   command: bundle exec grunt --environment {{ cartodb_environment }}
   become_user: "{{ ansible_ssh_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   when: cartodb_compile_assets

 - name: Touch app_config.yml to ensure it exists
   file: path="{{ cartodb_dir }}/config/app_config.yml" state=touch

 - name: Copy app_config.yml template
   template: src=app_config.yml.j2 dest="{{ cartodb_dir }}/config/app_config.yml"

 - name: Touch database.yml to ensure it exists
   file: path="{{ cartodb_dir }}/config/database.yml" state=touch

 - name: Copy database.yml template
   template: src=database.yml.j2 dest="{{ cartodb_dir }}/config/database.yml"

 - name: Create CartoDB database
   command: bundle exec rake db:create
   become_user: "{{ ansible_ssh_user }}"
   args:
     chdir: "{{ cartodb_dir }}"

 - name: Migrate CartoDB database
   command: bundle exec rake db:migrate
   become_user: "{{ ansible_ssh_user }}"
   args:
     chdir: "{{ cartodb_dir }}"

 - name: Create a cartodb user
   command: bundle exec rake cartodb:db:create_user SUBDOMAIN="{{ cartodb_user_subdomain }}" PASSWORD="{{ cartodb_user_password }}" EMAIL="{{ cartodb_user_email }}"
   become_user: "{{ ansible_ssh_user }}"
   args:
     chdir: "{{ cartodb_dir }}"

 - name: Add cartodb user subdomain to hosts file
   lineinfile: dest=/etc/hosts line="127.0.0.1 {{ cartodb_user_subdomain }}.{{ cartodb_hostname }}"

 - name: Add cartodb hostname to hosts file
   lineinfile: dest=/etc/hosts line="127.0.0.1 {{ cartodb_hostname }}"

 - name: Copy rails server job template
   template: src=cartodb_server.conf.j2 dest=/etc/init/cartodb_server.conf

 - name: Start the CartoDB rails server
   service: name=cartodb_server state=restarted
