---

 - name: Clone CartoDB Windshaft repo
   git: repo=https://github.com/CartoDB/Windshaft-cartodb.git dest={{ cartodb_windshaft_dir }} version={{ cartodb_windshaft_version }}

 - name: Chown cartodb_windshaft_dir to ansible_ssh_user
   file: path={{ cartodb_windshaft_dir }} state=directory recurse=yes owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}

 - name: Install apt dependencies
   apt: name={{ item }} state=present
   with_items:
     - libpango1.0-dev

 - name: Install npm dependencies
   npm: path={{ cartodb_windshaft_dir }}
   become_user: "{{ ansible_ssh_user }}"

 - name: Touch CartoDB Windshaft config file
   file: path="{{ cartodb_windshaft_dir }}/config/environments/{{ cartodb_environment }}.js"
         state=touch
         owner="{{ ansible_ssh_user }}"
         group="{{ ansible_ssh_user }}"

 - name: Copy template config
   template: src={{ cartodb_environment }}.js.j2 dest={{ cartodb_windshaft_dir }}/config/environments/{{ cartodb_environment }}.js
   become_user: "{{ ansible_ssh_user }}"

 - name: Copy CartoDB Windshaft upstart job
   template: src=cartodb_windshaft.conf.j2 dest=/etc/init/cartodb_windshaft.conf

 - name: Set permissions for CartoDB Windshaft service
   file: mode=0644 owner=root group=root path=/etc/init/cartodb_windshaft.conf

 - name: Restart CartoDB Windshaft upstart job
   service: name=cartodb_windshaft state=restarted
